/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOWG722_VERSION_H
#define PCMFLOWG722_VERSION_H

#define PCMFLOWG722_VERSION_MAJOR 0
#define PCMFLOWG722_VERSION_MINOR 1
#define PCMFLOWG722_VERSION_PATCH 0
#define PCMFLOWG722_VERSION_STR "0.1.0"

#endif // PCMFLOWG722_VERSION_H
