/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOWG722_VERSION_H
#define PCMFLOWG722_VERSION_H

#define PCMFLOWG722_VERSION_MAJOR 0
#define PCMFLOWG722_VERSION_MINOR 2
#define PCMFLOWG722_VERSION_PATCH 0
#define PCMFLOWG722_VERSION_STR "0.2.0"

#endif // PCMFLOWG722_VERSION_H
